###################################################################################
# Mentor Graphics Corporation
#
###################################################################################

#################
# Attributes
#################
set_attribute -name INFF -value "FALSE" -port -type string i_clk -design gatelevel 
set_attribute -name ax_width -value "18" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name ay_scan_in_width -value "18" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name az_width -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name bx_width -value "18" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name by_width -value "18" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name bz_width -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name scan_out_width -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name result_a_width -value "16" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name result_b_width -value "1" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name mode_sub_location -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name operand_source_max -value "input" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name operand_source_may -value "input" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name operand_source_mbx -value "input" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name operand_source_mby -value "input" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name preadder_subtract_a -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name preadder_subtract_b -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name signed_max -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name signed_may -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name signed_mbx -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name signed_mby -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name ay_use_scan_in -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name by_use_scan_in -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name delay_scan_out_ay -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name delay_scan_out_by -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name use_chainadder -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name enable_double_accum -value "false" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name load_const_value -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_a_0 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_a_1 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_a_2 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_a_3 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_a_4 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_a_5 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_a_6 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_a_7 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_b_0 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_b_1 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_b_2 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_b_3 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_b_4 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_b_5 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_b_6 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_b_7 -value "0" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name ax_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name ay_scan_in_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name az_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name bx_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name by_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name bz_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_sel_a_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name coef_sel_b_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name sub_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name negate_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name accumulate_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name load_const_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name output_clock -value "none" -instance cyclonev_mac_0 -design gatelevel 
set_attribute -name ax_width -value "18" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name ay_scan_in_width -value "18" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name az_width -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name bx_width -value "18" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name by_width -value "18" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name bz_width -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name scan_out_width -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name result_a_width -value "16" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name result_b_width -value "1" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name mode_sub_location -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name operand_source_max -value "input" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name operand_source_may -value "input" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name operand_source_mbx -value "input" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name operand_source_mby -value "input" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name preadder_subtract_a -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name preadder_subtract_b -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name signed_max -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name signed_may -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name signed_mbx -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name signed_mby -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name ay_use_scan_in -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name by_use_scan_in -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name delay_scan_out_ay -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name delay_scan_out_by -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name use_chainadder -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name enable_double_accum -value "false" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name load_const_value -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_a_0 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_a_1 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_a_2 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_a_3 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_a_4 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_a_5 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_a_6 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_a_7 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_b_0 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_b_1 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_b_2 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_b_3 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_b_4 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_b_5 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_b_6 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_b_7 -value "0" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name ax_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name ay_scan_in_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name az_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name bx_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name by_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name bz_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_sel_a_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name coef_sel_b_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name sub_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name negate_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name accumulate_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name load_const_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name output_clock -value "none" -instance cyclonev_mac_1 -design gatelevel 
set_attribute -name ax_width -value "18" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name ay_scan_in_width -value "18" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name az_width -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name bx_width -value "18" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name by_width -value "18" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name bz_width -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name scan_out_width -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name result_a_width -value "16" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name result_b_width -value "1" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name mode_sub_location -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name operand_source_max -value "input" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name operand_source_may -value "input" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name operand_source_mbx -value "input" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name operand_source_mby -value "input" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name preadder_subtract_a -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name preadder_subtract_b -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name signed_max -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name signed_may -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name signed_mbx -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name signed_mby -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name ay_use_scan_in -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name by_use_scan_in -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name delay_scan_out_ay -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name delay_scan_out_by -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name use_chainadder -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name enable_double_accum -value "false" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name load_const_value -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_a_0 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_a_1 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_a_2 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_a_3 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_a_4 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_a_5 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_a_6 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_a_7 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_b_0 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_b_1 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_b_2 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_b_3 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_b_4 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_b_5 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_b_6 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_b_7 -value "0" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name ax_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name ay_scan_in_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name az_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name bx_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name by_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name bz_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_sel_a_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name coef_sel_b_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name sub_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name negate_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name accumulate_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name load_const_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name output_clock -value "none" -instance cyclonev_mac_2 -design gatelevel 
set_attribute -name ax_width -value "18" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name ay_scan_in_width -value "18" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name az_width -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name bx_width -value "18" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name by_width -value "18" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name bz_width -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name scan_out_width -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name result_a_width -value "16" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name result_b_width -value "1" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name mode_sub_location -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name operand_source_max -value "input" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name operand_source_may -value "input" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name operand_source_mbx -value "input" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name operand_source_mby -value "input" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name preadder_subtract_a -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name preadder_subtract_b -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name signed_max -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name signed_may -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name signed_mbx -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name signed_mby -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name ay_use_scan_in -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name by_use_scan_in -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name delay_scan_out_ay -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name delay_scan_out_by -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name use_chainadder -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name enable_double_accum -value "false" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name load_const_value -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_a_0 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_a_1 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_a_2 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_a_3 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_a_4 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_a_5 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_a_6 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_a_7 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_b_0 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_b_1 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_b_2 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_b_3 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_b_4 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_b_5 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_b_6 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_b_7 -value "0" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name ax_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name ay_scan_in_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name az_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name bx_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name by_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name bz_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_sel_a_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name coef_sel_b_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name sub_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name negate_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name accumulate_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name load_const_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name output_clock -value "none" -instance cyclonev_mac_3 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62815 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62814 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62813 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62825 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62832 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62831 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62830 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62843 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62850 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62849 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62848 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62861 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62868 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62867 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62866 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62879 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62885 -design gatelevel 
set_attribute -name shared_arith -value "on" -instance ix19104z62890 -design gatelevel 
set_attribute -name extended_lut -value "on" -instance ix5537z62814 -design gatelevel 

##################
# Clocks
##################
create_clock { i_clk } -domain ClockDomain0 -name i_clk -period 40.000000 -waveform { 0.000000 20.000000 } -design gatelevel 
